import test from 'node:test';
import assert from 'node:assert/strict';
import { createApp } from '../app.js';
import { loadConfig } from '../config.js';
import { sign } from '../lib/http.js';

const baseConfig=(overrides={})=>({...loadConfig({NODE_ENV:'test',PORT:'0',SUPABASE_URL:'https://db.test',SUPABASE_ANON_KEY:'anon',SUPABASE_SERVICE_ROLE_KEY:'service',SUPABASE_STORAGE_BUCKET:'rfq-private',FRONTEND_ORIGIN:'https://front.test',APP_URL:'http://127.0.0.1',SESSION_SECRET:'12345678901234567890123456789012',MAX_FILE_BYTES:'10485760',MAX_TOTAL_UPLOAD_BYTES:'26214400',MAX_FILES:'10'},{allowIncomplete:true}),...overrides});
const uuid='11111111-1111-4111-8111-111111111111',fileUuid='22222222-2222-4222-8222-222222222222';
function mocks(overrides={}){let sequence=0;const calls=[];return {calls,database:{
  async createEnquiry(data){calls.push(['create',data]);return{id:uuid,reference:`PF-2026-${String(++sequence).padStart(6,'0')}`}},async uploadFile(path,file){calls.push(['upload',path,file])},async createFileRecord(id,path,file){calls.push(['file',id,path,file]);return{id:fileUuid}},async deleteFiles(paths){calls.push(['deleteFiles',paths])},async deleteEnquiry(id){calls.push(['delete',id])},async queueEmails(){return[{id:'job-1',kind:'CUSTOMER_CONFIRMATION'}]},async updateNotification(){},async authenticate(email,password){return email==='admin@test.example'&&password==='correct'?{access_token:'access',refresh_token:'refresh',expires_in:3600,user:{id:uuid,email,app_metadata:{role:'admin'}}}:null},async signOut(token){calls.push(['signOut',token])},async getUser(token){return token==='access'?{id:uuid,email:'admin@test.example',app_metadata:{role:'admin'}}:null},async refresh(){return null},async listEnquiries(filters){calls.push(['list',filters]);return[{id:uuid,reference:'PF-2026-000001'}]},async getEnquiry(id){return id===uuid?{id,reference:'PF-2026-000001',enquiry_files:[]}:null},async updateStatus(id,status,actor){calls.push(['status',id,status,actor])},async getFile(id){return id===fileUuid?{id,storage_path:`${uuid}/drawing.pdf`,mime_type:'application/pdf',original_filename:'drawing.pdf'}:null},async downloadFile(){return Buffer.from('%PDF-test')},...overrides},emails:{async deliverJobs(enquiry,jobs){calls.push(['email',enquiry,jobs])}}};}
async function running(options={}){const config=baseConfig(options.config),services=mocks(options.database);if(options.emails)services.emails=options.emails;const server=createApp({config,database:services.database,emails:services.emails,fetchImpl:options.fetchImpl||fetch,now:options.now});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const origin=`http://127.0.0.1:${server.address().port}`;return{...services,config,origin,close:()=>new Promise(resolve=>server.close(resolve))};}
function validForm(){const form=new FormData();Object.entries({name:'A Buyer',company:'Acme',email:'buyer@example.com',phone:'0114 000 0000',service:'Laser cutting',project_description:'Cut this component',material:'S275',thickness:'3 mm',quantity:'20',dimensions:'100 x 50 mm',finish:'As cut',tolerance:'Drawing',required_date:'2026-10-30',urgency:'Standard',privacy_consent:'true'}).forEach(([key,value])=>form.append(key,value));return form;}
const post=(origin,form)=>fetch(`${origin}/api/enquiries`,{method:'POST',headers:{Origin:'https://front.test'},body:form});

for(const [name,filename,type,content] of [
 ['PDF','drawing.pdf','application/pdf',Buffer.from('%PDF-1.7 test')],['DXF','drawing.dxf','application/dxf',Buffer.from('  0\nSECTION\n  2\nHEADER')],['STEP','part.step','application/step',Buffer.from('ISO-10303-21;\nHEADER;')],['image','photo.png','image/png',Buffer.from([137,80,78,71,13,10,26,10,1])]
]) test(`accepts a valid ${name} submission and stores its file`,async()=>{const app=await running();try{const form=validForm();form.append('drawings',new Blob([content],{type}),filename);const response=await post(app.origin,form),body=await response.json();assert.equal(response.status,201);assert.match(body.reference,/^PF-2026-\d{6}$/);assert.equal(body.summary.fileCount,1);assert.equal(app.calls.filter(x=>x[0]==='create').length,1);assert.equal(app.calls.filter(x=>x[0]==='file').length,1);}finally{await app.close();}});

test('accepts multiple allowed files',async()=>{const app=await running();try{const form=validForm();form.append('drawings',new Blob([Buffer.from('%PDF-1.7')],{type:'application/pdf'}),'a.pdf');form.append('drawings',new Blob([Buffer.from('ISO-10303-21;')],{type:'application/step'}),'b.stp');const response=await post(app.origin,form);assert.equal(response.status,201);assert.equal(app.calls.filter(x=>x[0]==='upload').length,2);}finally{await app.close();}});
for(const [label,mutate,error] of [
 ['missing required field',form=>form.delete('name'),'name is required'],['invalid email',form=>form.set('email','not-an-email'),'valid email'],['invalid extension',form=>form.append('drawings',new Blob(['echo bad'],{type:'text/plain'}),'bad.exe'),'not allowed'],['spoofed MIME',form=>form.append('drawings',new Blob(['not a pdf'],{type:'application/pdf'}),'bad.pdf'),'does not match']
])test(`rejects ${label}`,async()=>{const app=await running();try{const form=validForm();mutate(form);const response=await post(app.origin,form),body=await response.json();assert.equal(response.status,400);assert.match(body.error,new RegExp(error,'i'));assert.equal(app.calls.filter(x=>x[0]==='create').length,0);}finally{await app.close();}});
test('rejects an oversized file',async()=>{const app=await running({config:{maxFileBytes:8,maxTotalBytes:100000}});try{const form=validForm();form.append('drawings',new Blob([Buffer.from('%PDF-123456789')],{type:'application/pdf'}),'large.pdf');const response=await post(app.origin,form);assert.equal(response.status,413);}finally{await app.close();}});
test('cleans up enquiry and objects after storage failure',async()=>{const app=await running({database:{async uploadFile(){throw new Error('storage unavailable')}}});try{const form=validForm();form.append('drawings',new Blob([Buffer.from('%PDF-1.7')],{type:'application/pdf'}),'a.pdf');const response=await post(app.origin,form);assert.equal(response.status,503);assert.equal(app.calls.some(x=>x[0]==='delete'),true);}finally{await app.close();}});
test('returns a generic database failure without a false success',async()=>{const app=await running({database:{async createEnquiry(){throw new Error('database unavailable')}}});try{const response=await post(app.origin,validForm());assert.equal(response.status,500);assert.equal((await response.json()).error,'The request could not be completed');}finally{await app.close();}});
test('honeypot silently accepts without storing',async()=>{const app=await running();try{const form=validForm();form.set('website','spam');const response=await post(app.origin,form);assert.equal(response.status,200);assert.equal(app.calls.length,0);}finally{await app.close();}});
test('rate limits repeated submissions',async()=>{const app=await running();try{for(let i=0;i<5;i++)assert.equal((await post(app.origin,validForm())).status,201);const response=await post(app.origin,validForm());assert.equal(response.status,429);assert.equal(response.headers.get('retry-after'),'900');}finally{await app.close();}});
test('admin and file routes reject unauthorised users and carry noindex',async()=>{const app=await running();try{for(const path of ['/admin/api/enquiries',`/admin/api/files/${fileUuid}/download`]){const response=await fetch(app.origin+path);assert.equal(response.status,401);assert.match(response.headers.get('x-robots-tag'),/noindex/);}}finally{await app.close();}});
test('admin login rejects invalid credentials and accepts an admin',async()=>{const app=await running();try{let response=await fetch(`${app.origin}/admin/api/login`,{method:'POST',headers:{Origin:app.config.appUrl,'Content-Type':'application/json'},body:JSON.stringify({email:'admin@test.example',password:'bad'})});assert.equal(response.status,401);response=await fetch(`${app.origin}/admin/api/login`,{method:'POST',headers:{Origin:app.config.appUrl,'Content-Type':'application/json'},body:JSON.stringify({email:'admin@test.example',password:'correct'})});assert.equal(response.status,200);assert.match(response.headers.get('set-cookie'),/HttpOnly/);}finally{await app.close();}});
test('authenticated admin can list, search, filter, inspect, update, and download',async()=>{const app=await running();try{const auth=`pf_access=${encodeURIComponent(sign('access',app.config.sessionSecret))}; pf_csrf=csrf`;let response=await fetch(`${app.origin}/admin/api/enquiries?search=PF-1&status=NEW&service=Laser%20cutting&sort=asc`,{headers:{Cookie:auth}});assert.equal(response.status,200);assert.equal((await response.json()).enquiries.length,1);assert.deepEqual(app.calls.find(x=>x[0]==='list')[1],{search:'PF-1',status:'NEW',service:'Laser cutting',direction:'asc'});response=await fetch(`${app.origin}/admin/api/enquiries/${uuid}`,{headers:{Cookie:auth}});assert.equal(response.status,200);response=await fetch(`${app.origin}/admin/api/enquiries/${uuid}`,{method:'PATCH',headers:{Cookie:auth,Origin:app.config.appUrl,'X-CSRF-Token':'csrf','Content-Type':'application/json'},body:JSON.stringify({status:'QUOTED'})});assert.equal(response.status,200);assert.equal(app.calls.some(x=>x[0]==='status'&&x[2]==='QUOTED'),true);response=await fetch(`${app.origin}/admin/api/files/${fileUuid}/download`,{headers:{Cookie:auth}});assert.equal(response.status,200);assert.match(response.headers.get('content-disposition'),/drawing.pdf/);}finally{await app.close();}});
test('public config hides or displays WhatsApp only from configuration',async()=>{for(const [number,expected] of [['',null],['441142422733','https://wa.me/441142422733']]){const app=await running({config:{whatsappNumber:number}});try{const response=await fetch(`${app.origin}/api/public-config`,{headers:{Origin:'https://front.test'}}),body=await response.json();if(expected)assert.ok(body.whatsappUrl.startsWith(expected));else assert.equal(body.whatsappUrl,null);}finally{await app.close();}}});

test('rejects unapproved CORS origins',async()=>{const app=await running();try{const response=await fetch(`${app.origin}/api/enquiries`,{method:'POST',headers:{Origin:'https://evil.example'},body:validForm()});assert.equal(response.status,403);assert.equal(response.headers.get('access-control-allow-origin'),null);}finally{await app.close();}});
test('requires successful Turnstile verification when configured',async()=>{const app=await running({config:{turnstileSecretKey:'secret'},fetchImpl:async()=>new Response(JSON.stringify({success:false}),{status:200,headers:{'Content-Type':'application/json'}})});try{const response=await post(app.origin,validForm());assert.equal(response.status,400);assert.match((await response.json()).error,/verification/i);assert.equal(app.calls.length,0);}finally{await app.close();}});
test('stored enquiry remains successful when notification delivery later fails',async()=>{const app=await running({emails:{async deliverJobs(){throw new Error('provider down')}}});try{const response=await post(app.origin,validForm());assert.equal(response.status,201);assert.equal(app.calls.some(x=>x[0]==='create'),true);}finally{await new Promise(resolve=>setTimeout(resolve,5));await app.close();}});
test('cleans up after file metadata insert failure',async()=>{const app=await running({database:{async createFileRecord(){throw new Error('record insert failed')}}});try{const form=validForm();form.append('drawings',new Blob([Buffer.from('%PDF-1.7')],{type:'application/pdf'}),'a.pdf');const response=await post(app.origin,form);assert.equal(response.status,503);assert.equal(app.calls.some(x=>x[0]==='deleteFiles'),true);assert.equal(app.calls.some(x=>x[0]==='delete'),true);}finally{await app.close();}});
test('status updates require a matching CSRF token',async()=>{const app=await running();try{const auth=`pf_access=${encodeURIComponent(sign('access',app.config.sessionSecret))}; pf_csrf=expected`;const response=await fetch(`${app.origin}/admin/api/enquiries/${uuid}`,{method:'PATCH',headers:{Cookie:auth,Origin:app.config.appUrl,'X-CSRF-Token':'wrong','Content-Type':'application/json'},body:JSON.stringify({status:'WON'})});assert.equal(response.status,403);}finally{await app.close();}});
