import test from 'node:test';import assert from 'node:assert/strict';import { EmailService } from '../services/email.js';
const enquiry={id:'id',reference:'PF-2026-000001',name:'Buyer',company:'Acme',email:'buyer@example.com',phone:'1',service:'Laser cutting',project_description:'Parts',material:'Steel',thickness:'3',quantity:'2',dimensions:'10',finish:'None',tolerance:'Drawing',required_date:null,fileCount:1};
test('sends customer confirmation and Parkway notification without file URLs',async()=>{const sent=[],updates=[],service=new EmailService({resendApiKey:'key',emailFrom:'from@example.com',notificationEmail:'sales@example.com',appUrl:'https://api.example.com'},{async updateNotification(id,value){updates.push([id,value])}},async(url,options)=>{sent.push(JSON.parse(options.body));return new Response(JSON.stringify({id:'email-id'}),{status:200})});await service.deliverJobs(enquiry,[{id:'1',kind:'CUSTOMER_CONFIRMATION',attempts:0},{id:'2',kind:'PARKWAY_NOTIFICATION',attempts:0}]);assert.equal(sent.length,2);assert.equal(sent[0].to[0],enquiry.email);assert.equal(sent[1].to[0],'sales@example.com');assert.match(sent[1].html,/secure admin area/);assert.doesNotMatch(sent[1].html,/storage_path|supabase/);assert.equal(updates.every(x=>x[1].status==='SENT'),true);});
test('email provider failure queues retry and does not throw',async()=>{const updates=[],service=new EmailService({resendApiKey:'key',emailFrom:'from@example.com',notificationEmail:'sales@example.com',appUrl:'https://api.example.com'},{async updateNotification(id,value){updates.push(value)}},async()=>new Response('bad',{status:500}));await service.deliverJobs(enquiry,[{id:'1',kind:'CUSTOMER_CONFIRMATION',attempts:0}]);assert.equal(updates[0].status,'RETRY');assert.equal(updates[0].attempts,1);});


test('email retries use the same provider idempotency key',async()=>{
 const keys=[],service=new EmailService({resendApiKey:'key',emailFrom:'from@example.com'},{async updateNotification(){}},async(url,options)=>{keys.push(options.headers['Idempotency-Key']);return new Response(JSON.stringify({id:'email-id'}),{status:200})});
 const jobs=[{id:'stable-job-id',kind:'CUSTOMER_CONFIRMATION',status:'PROCESSING',attempts:1}];await service.deliverJobs(enquiry,jobs);await service.deliverJobs(enquiry,jobs);assert.deepEqual(keys,['parkway-notification/stable-job-id','parkway-notification/stable-job-id']);
});
